"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const react_1 = require("react");
const react_router_dom_1 = require("react-router-dom");
const AboutPage = () => {
    return (react_1.default.createElement("div", { id: "aboutPage" },
        react_1.default.createElement("div", { id: "aboutPage", className: "row justify-content-center" },
            react_1.default.createElement("div", { id: "aboutContent", className: "col-10 col-sm-10 col-xs-10 col-md-10 col-lg-8 col-xl-8" },
                react_1.default.createElement("p", null, "Dog Finder is a React appliction developed for training purposes to learn React."),
                react_1.default.createElement("ul", null,
                    react_1.default.createElement("li", null, "Created By: Brian Krueger"),
                    react_1.default.createElement("li", null, "Editor: Atom"),
                    react_1.default.createElement("li", null,
                        "Technologies:",
                        react_1.default.createElement("br", null),
                        react_1.default.createElement("ul", null,
                            react_1.default.createElement("li", null, "React"),
                            react_1.default.createElement("li", null, "React Router"),
                            react_1.default.createElement("li", null, "Redux"),
                            react_1.default.createElement("li", null, "Bootstrap"),
                            react_1.default.createElement("li", null, "Sass"),
                            react_1.default.createElement("li", null, "WebPack"))),
                    react_1.default.createElement("li", null,
                        "Data/API Sources:",
                        react_1.default.createElement("br", null),
                        react_1.default.createElement("ul", null,
                            react_1.default.createElement("li", null,
                                "Dog CEO: ",
                                react_1.default.createElement("a", { href: "https://dog.ceo" }, "https://dog.ceo"),
                                react_1.default.createElement("br", null),
                                react_1.default.createElement("ul", null,
                                    react_1.default.createElement("li", null, "Breed List: https://dog.ceo/api/breeds/list"),
                                    react_1.default.createElement("li", { className: "text-muted" }, "Random Image All Breeds (future): https://dog.ceo/api/breeds/image/random"),
                                    react_1.default.createElement("li", null,
                                        "Random Image Breed: https://dog.ceo/api/breed/",
                                        react_1.default.createElement("span", { className: "text-success" }, "breed"),
                                        "/image/random"),
                                    react_1.default.createElement("li", null,
                                        "Random Image Sub-Breed: https://dog.ceo/api/breed/",
                                        react_1.default.createElement("span", { className: "text-success" }, "breed"),
                                        "/",
                                        react_1.default.createElement("span", { className: "text-success" }, "subbreed"),
                                        "/image/random"),
                                    react_1.default.createElement("li", null, "List All (Used for Search): https://dog.ceo/api/breeds/list/all"))),
                            react_1.default.createElement("li", null,
                                "Wikipedia: for dog details",
                                react_1.default.createElement("br", null),
                                react_1.default.createElement("ul", null,
                                    react_1.default.createElement("li", null,
                                        "Search: https://en.wikipedia.org/w/api.php?format=json&origin=*&action=query&list=search&srlimit=1&srsearch=",
                                        react_1.default.createElement("span", { className: "text-success" }, "breed%20subBreed"),
                                        "%20dog"),
                                    react_1.default.createElement("li", null,
                                        "Details Extract: https://en.wikipedia.org/w/api.php?format=json&origin=*&action=query&prop=extracts&exintro&redirects=1&pageids=",
                                        react_1.default.createElement("span", { className: "text-success" }, "pageId")))))))))));
};
exports.default = react_router_dom_1.withRouter(AboutPage);
//# sourceMappingURL=aboutPage.js.map